### ISSUE TITLE
Single Tasks get sent but dont have $lookfor or $trigger changed

### ISSUE THREAD

**Issue by bubonicfred** [Gnopps/ObsidianTodo#1]
This may be because I'm running a modified version to send to todotxt(making progress) but sometimes if there's only one task it doesn't get its $lookfor or $trigger changed and therefore gets inputted multiple times. My working code is below.
Aside from some comments and importing a module (PsTodoTxt) the only line I've changed is the one starting  ` $fileContent | Select-String -Pattern `

```
Register-ObjectEvent $fsw Changed -SourceIdentifier FileChanged -Action {
    $name = $Event.SourceEventArgs.Name
    $changeType = $Event.SourceEventArgs.ChangeType
    $timeStamp = $Event.TimeGenerated
    $fileContent = (Get-Content $folder$name)
#    Write-Host "The file '$name' was $changeType at $timeStamp" -fore green
   if ($fileContent -match $trigger) {
    $fileContent | Select-String -Pattern ".*$($lookfor)" -AllMatches | ForEach-Object { $_.Matches } | ForEach-Object {  $todo = ($_.Value).TrimEnd($lookfor); $todoobj = ConvertTo-TodoTxt $todo; Export-TodoTxt $todoobj -Path c:\output.txt -Append
    $fileContent | ForEach-Object { $_ -replace $lookfor, $replaceto -replace " $($trigger)", '' -replace $trigger, '' } | Set-Content $folder$name }
    }}
```

**Comment by Gnopps** [comment]
Thanks for reporting this! Are you able to please send only the code as it ought to be (i.e. without the references to todotxt)

**Comment by bubonicfred** [comment]
I've based this off a fresh copy of your script to double check and I still get this bug. 
My code is shown with the reference to todotxt changed to simply appending the file. Aside from the below the only other change is setting directory. 

```
   if ($fileContent -match $trigger) {
    $fileContent | Select-String -Pattern ".*$($lookfor)" -AllMatches | ForEach-Object { $_.Matches } | ForEach-Object { $todo = ($_.Value).TrimEnd($lookfor); Add-Content -Path C:\Users\ciara\.personal\todo.txt -Value $todo
    $fileContent | ForEach-Object { $_ -replace $lookfor, $replaceto -replace " $($trigger)", '' -replace $trigger, '' } | Set-Content $folder$name }
    }}
```

**Comment by Gnopps** [comment]
Thanks. I'm not running this myself right now as I've had to change computer, so I can't test it myself. The proposed code is still referencing a local file however. Would you have a correction that works out of the box with emailing?

**Comment by bubonicfred** [comment]
Whoops, I though you just meant without dependencies. 
I'm guessing the renaming command somehow clashes with the sending command, chucking a Start-Sleep in seems to fix it, will file a PR in a second

**Comment by Gnopps** [comment]
Thanks for your help with this!
